root = "../.."
tmp_dir = "services/auth/tmp"

[build]
cmd = "go build -o ./services/auth/tmp/main.exe ./services/auth"
bin = "services/auth/tmp/main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
