package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/services/staff/generated"
	"backend/services/staff/model"
	"context"
)

// FindStaffByID is the resolver for the findDriverByID field.
func (r *entityResolver) FindStaffByID(ctx context.Context, id string) (*model.Staff, error) {
	return r.svc.FindStaffByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
