package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/packages/middleware"
	"backend/services/staff/generated"
	"backend/services/staff/model"
	"context"
)

// CreateStaff is the resolver for the createDriver field.
func (r *mutationResolver) CreateStaff(ctx context.Context, input model.CreateStaffInput) (*model.Staff, error) {
	return r.svc.CreateStaff(ctx, input)
}

// UpdateStaff is the resolver for the updateDriver field.
func (r *mutationResolver) UpdateStaff(ctx context.Context, id string, input model.UpdateStaffInput) (*model.Staff, error) {
	return r.svc.UpdateStaff(ctx, id, input)
}

// DeleteStaff is the resolver for the deleteDriver field.
func (r *mutationResolver) DeleteStaff(ctx context.Context, id string) (bool, error) {
	return r.svc.DeleteStaff(ctx, id)
}

// Staff is the resolver for the staff field.
func (r *queryResolver) Staff(ctx context.Context, id string) (*model.Staff, error) {
	return r.svc.GetStaff(ctx, id)
}

// StaffList is the resolver for the staffList field.
func (r *queryResolver) StaffList(ctx context.Context, tenantID *string) (*model.StaffConnection, error) {
	tid := middleware.GetTenantID(ctx)
	if tenantID != nil {
		tid = *tenantID
	}
	return r.svc.ListStaff(ctx, tid)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
