package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/packages/middleware"
	"backend/services/drivers/generated"
	"backend/services/drivers/model"
	"context"
)

// CreateDriver is the resolver for the createDriver field.
func (r *mutationResolver) CreateDriver(ctx context.Context, input model.CreateDriverInput) (*model.Driver, error) {
	return r.svc.CreateDriver(ctx, input)
}

// UpdateDriver is the resolver for the updateDriver field.
func (r *mutationResolver) UpdateDriver(ctx context.Context, id string, input model.UpdateDriverInput) (*model.Driver, error) {
	return r.svc.UpdateDriver(ctx, id, input)
}

// DeleteDriver is the resolver for the deleteDriver field.
func (r *mutationResolver) DeleteDriver(ctx context.Context, id string) (bool, error) {
	return r.svc.DeleteDriver(ctx, id)
}

// Driver is the resolver for the driver field.
func (r *queryResolver) Driver(ctx context.Context, id string) (*model.Driver, error) {
	return r.svc.GetDriver(ctx, id)
}

// Drivers is the resolver for the drivers field.
func (r *queryResolver) Drivers(ctx context.Context, tenantID *string) (*model.DriverConnection, error) {
	tid := middleware.GetTenantID(ctx)
	if tenantID != nil {
		tid = *tenantID
	}
	return r.svc.ListDrivers(ctx, tid)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
