package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/services/drivers/generated"
	"backend/services/drivers/model"
	"context"
)

// FindDriverByID is the resolver for the findDriverByID field.
func (r *entityResolver) FindDriverByID(ctx context.Context, id string) (*model.Driver, error) {
	return r.svc.FindDriverByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
