// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateStaffInput struct {
	TenantID          string  `json:"tenantId"`
	Name              string  `json:"name"`
	Email             *string `json:"email,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	Role              *string `json:"role,omitempty"`
	LicenseNumber     *string `json:"licenseNumber,omitempty"`
	LicenseClass      *string `json:"licenseClass,omitempty"`
	LicenseExpiry     *string `json:"licenseExpiry,omitempty"`
	DateOfBirth       *string `json:"dateOfBirth,omitempty"`
	Address           *string `json:"address,omitempty"`
	EmergencyContact  *string `json:"emergencyContact,omitempty"`
	EmergencyPhone    *string `json:"emergencyPhone,omitempty"`
	Status            *string `json:"status,omitempty"`
	AssignedVehicleID *string `json:"assignedVehicleId,omitempty"`
	Notes             *string `json:"notes,omitempty"`
	HireDate          *string `json:"hireDate,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Staff struct {
	ID                string  `json:"id"`
	TenantID          string  `json:"tenantId"`
	Name              string  `json:"name"`
	Email             *string `json:"email,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	Role              string  `json:"role"`
	LicenseNumber     *string `json:"licenseNumber,omitempty"`
	LicenseClass      *string `json:"licenseClass,omitempty"`
	LicenseExpiry     *string `json:"licenseExpiry,omitempty"`
	DateOfBirth       *string `json:"dateOfBirth,omitempty"`
	Address           *string `json:"address,omitempty"`
	EmergencyContact  *string `json:"emergencyContact,omitempty"`
	EmergencyPhone    *string `json:"emergencyPhone,omitempty"`
	Status            string  `json:"status"`
	AssignedVehicleID *string `json:"assignedVehicleId,omitempty"`
	Notes             *string `json:"notes,omitempty"`
	HireDate          *string `json:"hireDate,omitempty"`
	CreatedAt         string  `json:"createdAt"`
	UpdatedAt         string  `json:"updatedAt"`
}

func (Staff) IsEntity() {}

type StaffConnection struct {
	Items []*Staff `json:"items"`
	Total int      `json:"total"`
}

type UpdateStaffInput struct {
	Name              *string `json:"name,omitempty"`
	Email             *string `json:"email,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	Role              *string `json:"role,omitempty"`
	LicenseNumber     *string `json:"licenseNumber,omitempty"`
	LicenseClass      *string `json:"licenseClass,omitempty"`
	LicenseExpiry     *string `json:"licenseExpiry,omitempty"`
	DateOfBirth       *string `json:"dateOfBirth,omitempty"`
	Address           *string `json:"address,omitempty"`
	EmergencyContact  *string `json:"emergencyContact,omitempty"`
	EmergencyPhone    *string `json:"emergencyPhone,omitempty"`
	Status            *string `json:"status,omitempty"`
	AssignedVehicleID *string `json:"assignedVehicleId,omitempty"`
	Notes             *string `json:"notes,omitempty"`
	HireDate          *string `json:"hireDate,omitempty"`
}
